### PR TITLE
Make submission dialogue explain the error in detail

### PR DESCRIPTION
**Pull request by yutanakamura-tky**
Current submission dialogues output unreadble error messages like below for some exceptions:

screenshot 2024-10-20 at 17 57 19

This pull request passes the exception message from Submission.new_submission() to submission dialogues to be more user-friendly.

### CODE REVIEW

**Comment by abhishekkrthakur** [comment]
the reason we dont throw the error is because we dont want to leak any information. curious competitors can "hack" the error and print out the solution file in the error :)

**Comment by yutanakamura-tky** [comment]
Thank you for the background information and I understand the situation.

Then how about (i) redefining an error message in app.py instead of passing through the exception as it is and (ii) narrow the exception coverage to the minimum (i.e., only the excess of submission number and the late submit)?

I will update this pull request later and I appreciate it if you could give me a comment.

**Comment by yutanakamura-tky** [comment]
Thank you for your prompt reply, I will recheck what exception should be covered at least:)

**Comment by abhishekkrthakur** [comment]
thanks. ill do the same on my end :)

**Comment by yutanakamura-tky** [comment]
@abhishekkrthakur I have updated the pull request! :)

- I have comprehensively traced functional step during new submission and checked what custom exceptions can be thrown
- As a result, I found that Hugging Face API Connection error should be convered and this one extra coverage is enough

**Review by abhishekkrthakur — APPROVED** [review]

**Pull request merged**
